<a href="https://colab.research.google.com/github/Benzamin-003/Deeplearning/blob/main/PyTorch_properties.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
x=torch.rand(3,3)
print(x)

tensor([[0.5831, 0.9437, 0.2703],
        [0.8472, 0.9000, 0.8326],
        [0.5303, 0.4064, 0.4072]])


In [ ]:
torch.cuda.is_available()

True

In [ ]:
x=torch.empty(2,3)
x

tensor([[1.2064e-33, 0.0000e+00, 9.4427e-34],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [ ]:
x=torch.zeros(4,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
x=torch.ones(2,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
import numpy as np
arr = np.array([[1,1,2,2],
 [3,3,4,4]])
arr

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [ ]:
x=torch.tensor([[1,2],[3,4]],dtype=float)
#properties of torch
print(x.size())
print(x.dtype)
print(x.device)

torch.Size([2, 2])
torch.float64
cpu


In [ ]:
x=np.array([[1,2],[3,4]],dtype=float)
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# Indexing
print(x[:,1])

tensor([2., 4.], dtype=torch.float64)


In [ ]:
# Reshaping
x=torch.arange(2,33,2)
x=x.view(4,4)
x

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32]])

In [ ]:
if torch.cuda.is_available():
  tensor_gpu=x.to("cuda")
  print(tensor_gpu)


tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24],
        [26, 28, 30, 32]], device='cuda:0')


In [ ]:
x=torch.tensor([[1,2],[3,4]],device='cuda:0')
x.device

device(type='cuda', index=0)

In [ ]:
x=torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(x[0])
print(x[1,2])
print(x[-1])
print(x[:,0])
print(x[0:2,:])
print(x[:,1:])
print(x[::2,::2])

tensor([10, 20, 30])
tensor(60)
tensor([70, 80, 90])
tensor([10, 40, 70])
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([[20, 30],
        [50, 60],
        [80, 90]])
tensor([[10, 30],
        [70, 90]])


In [ ]:
#Fancy Indexing
rows=torch.tensor([0,2])
cols=torch.tensor([1,2])
print(x[rows,cols])

tensor([20, 90])


In [ ]:
#Boolean mask
mask=x>50
print(mask)
print(x[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [ ]:
x[0,2]=25
print(x)
x[:,1]=torch.tensor([111,222,333])
print(x)

tensor([[ 10, 111,  25],
        [ 40, 222,  60],
        [ 70, 333,  90]])
tensor([[ 10, 111,  25],
        [ 40, 222,  60],
        [ 70, 333,  90]])


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
import time

In [ ]:
a=np.random.rand(5000,5000)
start=time.time()
np.dot(a,a)
print('Numpy Time: ',time.time()-start)

a_t=torch.rand(5000,5000,device='cuda')
torch.cuda.synchronize()
start = time.time()
torch.matmul(a_t,a_t)
torch.cuda.synchronize()
print('PyTorch GPU time:', time.time() - start)



Numpy Time:  4.250982761383057
PyTorch GPU time: 0.27414608001708984
